spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003172
  
server:
  port: 8090
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log


# DataSource
spring.datasource.url: jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: rootroot
