spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171

server:
  port: 8080

logging:
  file: /opt/logs/100003171/apollo-configservice.log

# DataSource
spring.datasource.url: jdbc:mysql://localhost:3306/ApolloConfigDB?characterEncoding=utf8&useSSL=false
spring.datasource.username: root
spring.datasource.password: rootroot
